steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core 8'
  inputs:
    version: 8.0.x
 
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'


 
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
 
 
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration release --output $(build.artifactstagingdirectory) /property:PublishWithAspNetCoreTargetManifest=false'
    zipAfterPublish: false
 
- task: PublishBuildArtifacts@1
  displayName: 'Openshift'
  inputs:
    ArtifactName: ONS.PMO.Integracao.Api
    pathToPublish: $(build.artifactstagingdirectory)/ONS.PMO.Integracao.Api
